rename_to_match_products = {
    "objectid": "order_id",
    "NoPML1010": "PMLkit1010",
    "NoPetrifilm": "PetrifilmTests",
    "NoOasisTablets": "PurificationTabletsOasis",
    "NoHealthClub": "HealthClubExerciseBook",
    "NoChlorineStrips50": "ChlorineStrips50",
    "NoFlyers": "Flyers",
    "NoKisiKofiBooks": "KisiKofiBook",
    "NoCalendars": "Calendars",
    "NoWashHandsPoster": "WashHandsPoster",
    "NoBackpacks": "Backpack",
    "NoIncubationBags": "IncubationBag",
    "NoWhirlpaks": "Whirlpaks",
    "NoAABatteries": "Aabattery",
    "NoHealthClub": "HealthClubExerciseBook",
    "NoKisiKofiBooks": "KisiKofiBook",
    "NoCalendars": "Calendars",
    "NoCardboards": "Cardboards",
    "NoCertificatesCompletion": "CertificateCompletion",
    "NoFlyers": "Flyers",
    "NoKisiKofiFlyers": "KisiKofiFlyer",
    "NoHats": "Hat",
    "NoPML1010": "PMLkit1010",
    "NoPML1510": "PMLkit1510UV",
    "NoPML2525": "PMLkit2525",
    "NoBWVeronicaBucketLabels": "BWVeronicaBucketLabels",
    "NoGAVeronicaBucketLabels": "GAVeronicaBucketLabels",
    "NoUVLights": "UVLights",
    "NoEdManuals": "EducationManuals",
    "NoTrainManuals": "TrainingManuals",
    "NoMarkers": "Markers",
    "NoPencils": "Pencils",
    "NoPipettes": "Pipettes",
    "NoPosters": "Posters",
    "NoWashHandsPoster": "WashHandsPoster",
    "NoPoloShirts": "PoloShirt",
    "NoTeeShirts": "TeeShirt",
    "NoWaterSpreaders": "WaterSpreaders",
    "NoOasisTablets": "PurificationTabletsOasis",
    "NoColilert": "ColilertTubes",
    "NoPetrifilm": "PetrifilmTests",
    "NoChlorineStrips50": "ChlorineStrips50",
    "NoBWBuckets": "BrightWaterVeronicaBuckets",
    "NoGABuckets": "GrowthAidVeronicaBuckets",
}

rename_to_match_db_columns = {
    value: key for key, value in rename_to_match_products.items()
}

# items in this dict are ones that can be ordered and have a corresponding item in inventory
rename_to_match_inv = {
    "NoBackpacks": "backpack",
    "NoIncubationBags": "incub_bag",
    "NoWhirlpaks": "whirl_bag",
    "": "ziploc_bag",
    "NoAABatteries": "aa_battery",
    "NoHealthClub": "health_club_book",  # not sure here
    "NoKisiKofiBooks": "kisi_book",
    "NoCalendars": "calendar_25",  # multiple year calendars?
    "NoCardboards": "cardboard_set",
    "NoCertificatesCompletion": "certificate_comp",
    "NoFlyers": "flyer",
    "NoKisiKofiFlyers": "flyer_kisi",
    "NoWashHandsPoster": "flyer_hands",
    "NoHats": "hat",
    "NoPML1010": "PML1010",
    "NoBWVeronicaBucketLabels": "bucket_label",
    "NoGAVeronicaBucketLabels": "bucket_label_ga",
    "NoUVLights": "uv_light",
    "NoEdManuals": "manual_ed_24",
    "NoTrainManuals": "manual_train_24",
    "NoMarkers": "marker",
    "NoPencils": "pencil",
    "NoPipettes": "pipette_10",
    "": "rubber_band",
    "NoPoloShirts": "polo_shirt",
    "NoTeeShirts": "tee_shirt",
    "NoWaterSpreaders": "spreader",
    "NoOasisTablets": "oasis_50",
    "NoPetrifilm": "petrifilm",
    "NoColilert": "colilert",
    "NoChlorineStrips50": "chlorine_test_50",
    "": "umbrella",
    "NoBWBuckets": "veronica_bucket",
}

pretty_names = {
    "Backpack": "SWE backpack",
    "IncubationBag": "Bag, Incubation",
    "Whirlpaks": "Bag, Whirlpack",
    #  '':'Bag, Ziplock, Gallon',
    "Aabattery": "Battery AA",
    "HealthClubExerciseBook": "Book, Health Club Activity Guide",
    "KisiKofiBook": "Book, Kisi and Kofi",
    "Calendars": "Calendar, 2025",
    "Cardboards": "Cardboard, set of 2, with rubber bands",
    "CertificateCompletion": "Certificate, Completion",
    "Flyers": "Flyer, Family A4",
    "KisiKofiFlyer": "Flyer, Kisi and Kofi",
    "WashHandsPoster": "Flyer, Wash Your Hands A4",
    "Hat": "Hat",
    "PMLkit1010": "Kit, PML, (10 Colilert, 10 Pipettes, 10 Whirlpack Bags)",
    "BWVeronicaBucketLabels": "Labels, Veronica Bucket, BWF",
    "GAVeronicaBucketLabels": "Labels, Veronica Bucket, GA",
    "UVLights": "Light, UV",
    "EducationManuals": "Manual, Education (2024 Edition)",
    "TrainingManuals": "Manual, Training (2024 Edition)",
    "Markers": "Marker, Permanent",
    "Pencils": "Pencil, BWF",
    "Pipettes": "Pipettes, (10-Pack)",
    #  '':'Rubber Bands',
    "PoloShirt": "Shirt, Polo",
    "TeeShirt": "Shirt, Tee",
    "WaterSpreaders": "Spreader",
    "PurificationTabletsOasis": "Tablet, Oasis Water Purification, 50-ct. Carton",
    "PetrifilmTests": "Test, Petrifilm Plate",
    "ColilertTubes": "Test, Colilert Tube",
    "ChlorineStrips50": "Tests, Chlorine Residual Strips, 50 ct. Carton",
    #  '':'Umbrella, Gift',
    "BrightWaterVeronicaBuckets": "Veronica Bucket, Bright Water",
}
